/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Comment: typeof import('./src/components/Comment.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    GoodsChoice: typeof import('./src/components/GoodsChoice.vue')['default']
    GoodsLists: typeof import('./src/components/GoodsLists.vue')['default']
    MultiSettle: typeof import('./src/components/MultiSettle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settle: typeof import('./src/components/Settle.vue')['default']
    ShopCart: typeof import('./src/components/ShopCart.vue')['default']
    Tabbar: typeof import('./src/components/Tabbar.vue')['default']
  }
}
