/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Cart: typeof import('./src/components/Cart.vue')['default']
    GoodLists: typeof import('./src/components/GoodLists.vue')['default']
    GoodsLists: typeof import('./src/components/GoodsLists.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShopCart: typeof import('./src/components/ShopCart.vue')['default']
    Tabbar: typeof import('./src/components/Tabbar.vue')['default']
  }
}
